fix: run tests on ubuntu-22.04 to support python3.7
ubuntu-latest (24.04) does not support python3.7,
see https://github.com/actions/python-versions/blob/d75b46f6585cbd8749cc6cff669100a406746964/versions-manifest.json#L13066-L13092

from https://github.com/lidatong/dataclasses-json/actions/runs/25035565345/job/73326350509?pr=571:

```
Error: The version '3.7' with architecture 'x64' was not found for Ubuntu 24.04.
```