Enable mypy to find dataclasses_json when installed
Imagine a project that uses dataclasses_json:

  $ cat tiny.py
  import dataclasses_json

  # deliberate type error
  dataclasses_json.config(42)

Now I want to use mypy to typecheck that code. Fail:

  $ mypy tiny.py
  tiny.py:1: error: Cannot find module named 'dataclasses_json'
  tiny.py:1: note: See https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports

The "workaround" is to suppress mypy:

  import dataclasses_json     # type: ignore

which means the type annotations in dataclasses_json do nothing, and
mypy does not find my type error.

Turns out it's very easy to make a library visible to mypy: just add
empty file py.typed to its package directory. With this change, mypy
can find dataclasses_json and can make use of its type annotations:

  $ mypy tiny.py
  tiny.py:4: error: Argument 1 to "config" has incompatible type "int"; expected "Optional[Dict[Any, Any]]"